default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  host: localhost
  username: postgres
  password: password

test:
  <<: *default
  database: myapp_test
  host: localhost
  username: postgres
  password: password

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV["DATABASE_NAME"] %>
    host: dpg-cvg1h0dsvqrc73d5fln0-a
    username: <%= ENV["DATABASE_USER"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>

  cache:
    <<: *primary_production
    database: <%= ENV["DATABASE_NAME"] %>_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: <%= ENV["DATABASE_NAME"] %>_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: <%= ENV["DATABASE_NAME"] %>_cable
    migrations_paths: db/cable_migrate
